name: Code Checks

on:
  pull_request:
  push:
    
jobs:
  makers-devops:
    uses: Infineon/makers-devops/.github/workflows/code_checks.yml@main
    with:
      project-yaml: config/project.yml
      user-yaml: config/user.yml
    secrets: inherit

